name: branch-protection
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04-arm
        ruby:
          - 3.3.10
          - 3.4.8
          - 4.0.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler --no-document
      - run: bundle
      - run: rake
