name: branch-protection
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04-arm
        ruby:
          - 3.3.12
          - 3.4.10
          - 4.0.6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler --no-document
      - run: bundle
      - run: rake
