name: Test suite

on:
  - push

env:
  CI: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6.9
          - 2.7.5
          - 3.0.3
          - 3.1.0
    steps:
      - uses: actions/checkout@v2
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: gem install bundler --version 2.3.4 --no-document
      - run: bundle
      - run: rake
