name: Test suite

on:
  - push

env:
  CI: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5.8
          - 2.6.6
          - 2.7.1
    steps:
      - name: Setup Ruby
        uses: eregon/use-ruby-action@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Bundler
        run: gem install bundler --version 2.1.2 --no-document

      - name: Install gems
        run: bundle

      - name: Run tests
        run: rake
