name: Test suite

on:
  - push

env:
  CI: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.0.6
          - 3.1.4
          - 3.2.3
          - 3.3.0
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler --version 2.5.5 --no-document
      - run: bundle
      - run: rake
