name: Test suite

on:
  - push

env:
  CI: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7.7
          - 3.0.5
          - 3.1.3
          - 3.2.1
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: gem install bundler --version 2.4.7 --no-document
      - run: bundle
      - run: rake
