name: Test suite

on:
  - push

env:
  CI: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.2.6
          - 3.3.7
          - 3.4.1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler --version 2.6.3 --no-document
      - run: bundle
      - run: rake
