name: Test suite

on:
  - push

jobs:
  run-tests:
    name: Run tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ruby:
          - 3.2.8
          - 3.3.8
          - 3.4.4
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ruby/setup-ruby@a9bfc2ecf3dd40734a9418f89a7e9d484c32b990
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler --version 2.7.0 --no-document
      - run: bundle
      - run: rake
